### ISSUE TITLE
Download most popular movie of the day/week

### ISSUE THREAD

**Issue by jdart** [binhex/moviegrabber#3]
Hi Devs,

It would be neat if I could setup moviegrabber to to download the n most downloaded movie of the week. Newznab sites report how many "grabs" each title has had but I don't think the api allows you to sort by that field so it might be tricky. Is there a way to do this with MG?

Thanks!

**Comment by binhex** [comment]
this could be done using torrentfreaks top 10 rss feed, as they do something similar by aggregating all the index sites search result hits and producing a most popular list, its a good idea and def has possibilities, i will add it to my list, thanks for the suggestion.

can i ask what your main usage of MG is, are you using this for usenet content or torrents?.

p.s in case you wanna check out the rss feed its here:- http://torrentfreak.com/category/dvdrip/feed/

**Comment by jdart** [comment]
It's usenet/sabnzbd only for me. Come to think of it couch potato does something like this already, might not be worth the trouble. If only I could get couch potato to actually work!
