### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by avenantsoftware** [binhex/moviegrabber#5]
I run moviegrabber from a raspberry pi (the latest development version of moviegrabber), I started to notice that 25 percent of the raspberry pi's memory is constantly used by moviegrabber, other services such as sickbeard and couchpotato don't use this much memory...

**Comment by binhex** [comment]
hi, i am currently in a massive re-write of moviegrabber, so i cant really comment at the mo as to this particular issue, hopefully things will be improved once i get the new version out.

**Comment by matt-seaton** [comment]
Is there an ETA on the new version?  Any way to help?
