### ISSUE TITLE
IMDb JSON down

### ISSUE THREAD

**Issue by j038lack** [binhex/moviegrabber#7]
Hi binhex,

Its been a long time since i last reported an issue. But it seems i'm getting IMDb JSON down errors. I have reload a fresh master version and reconfigured the basic minimum. but still getting IMDb JSON down errors.

In the mean time i did try radarr  for the first time which still does not do what your Moviegrabber can do. setting up lists is a pain. I want moviegrabber back.......

Thanks for the great script
J03

**Comment by binhex** [comment]
I've fixed this up in the development branch, are you running unraid or have docker installed? If so then your easiest route is to simply pull down the docker image binhex/arch-moviegrabber
